include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SentinelPref
SentinelPref_FILES = SentRootListController.m
SentinelPref_INSTALL_PATH = /Library/PreferenceBundles
SentinelPref_EXTRA_FRAMEWORKS = CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk
